/** @type {import('tailwindcss').Config} */
export default {
  // src/GloobalApp.jsx is generated by ../build_app.mjs, so scanning src/ is
  // enough for the preview build. frontend/ is listed too so a class that
  // only exists in a module not yet wired into build_app.mjs's module list
  // still gets its utility emitted instead of silently rendering unstyled.
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
    "../frontend/**/*.{js,jsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
