// src/domain/risk/riskCodes.js
var RISK_CODE = {
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INVALID_METHOD: "INVALID_METHOD",
  INVALID_BALANCE: "INVALID_BALANCE",
  INSUFFICIENT_BANK: "INSUFFICIENT_BANK",
  INSUFFICIENT_COMBINED: "INSUFFICIENT_COMBINED"
};

